# Generated by Django 4.2.7 on 2023-12-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskName', models.CharField(max_length=100)),
                ('taskDescription', models.TextField()),
                ('isComplete', models.BooleanField(default=False)),
                ('assign_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
