# Generated by Django 4.2.7 on 2023-12-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_taskcategory_taskname'),
        ('task', '0002_rename_iscomplete_taskmodel_iscompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='category_name',
            field=models.ManyToManyField(to='category.taskcategory'),
        ),
    ]
