# Generated by Django 4.2.7 on 2023-12-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_taskmodel_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='category_name',
            new_name='category',
        ),
    ]
