# Generated by Django 4.2.7 on 2023-12-27 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='model_name',
            new_name='brand_name',
        ),
    ]
