# Generated by Django 4.2.7 on 2023-12-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_model_name_brand_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/static/'),
        ),
    ]
